namespace CodexHomeManager;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel rootLayout = null!;
    private GroupBox grpPaths = null!;
    private TableLayoutPanel pathsLayout = null!;
    private Label lblStateHome = null!;
    private Label lblAuthHome = null!;
    private Label lblProfilesRoot = null!;
    private Label lblSharedStoreHome = null!;
    private Label lblTargetHome = null!;
    private Label lblAppExe = null!;
    private TextBox txtStateHome = null!;
    private TextBox txtAuthHome = null!;
    private TextBox txtProfilesRoot = null!;
    private TextBox txtSharedStoreHome = null!;
    private TextBox txtTargetHome = null!;
    private TextBox txtAppExe = null!;
    private Button btnBrowseState = null!;
    private Button btnBrowseAuth = null!;
    private Button btnBrowseProfilesRoot = null!;
    private Button btnBrowseShared = null!;
    private Button btnBrowseTarget = null!;
    private Button btnBrowseAppExe = null!;
    private GroupBox grpActions = null!;
    private FlowLayoutPanel actionLayout = null!;
    private Button btnUseDefaults = null!;
    private Button btnLoadSessions = null!;
    private Button btnLoadSharedSessions = null!;
    private Button btnPrepareHome = null!;
    private Button btnImportSelected = null!;
    private Button btnRepairTargetHome = null!;
    private Label lblProfileName = null!;
    private ComboBox cmbProfiles = null!;
    private Button btnRefreshProfiles = null!;
    private Button btnSaveProfile = null!;
    private Button btnCreateEmptyProfile = null!;
    private Button btnRenameProfile = null!;
    private Button btnDeleteProfile = null!;
    private Button btnEditProfileContents = null!;
    private Button btnSetDefaultLaunchProfile = null!;
    private Button btnApplyProfile = null!;
    private Button btnImportProfile = null!;
    private Button btnExportProfile = null!;
    private Button btnLaunchDefaultProfile = null!;
    private Button btnManageSharedStoreDefaults = null!;
    private Button btnSwitchProfileAndLaunch = null!;
    private Button btnCloseApp = null!;
    private Button btnLaunchApp = null!;
    private CheckBox chkOverwriteTarget = null!;
    private CheckBox chkRefreshUpdatedAt = null!;
    private CheckBox chkAddWorkspaceHint = null!;
    private CheckBox chkAutoSyncConfigChanges = null!;
    private Label lblStatus = null!;
    private Label lblAppStatus = null!;
    private Label lblProviderStatus = null!;
    private Label lblDefaultProfileStatus = null!;
    private Label lblWatchStatus = null!;
    private SplitContainer mainSplit = null!;
    private GroupBox grpSessions = null!;
    private TableLayoutPanel sessionsLayout = null!;
    private Label lblSessionCount = null!;
    private DataGridView sessionsGrid = null!;
    private GroupBox grpDetails = null!;
    private TableLayoutPanel detailsLayout = null!;
    private Label lblSelectedId = null!;
    private Label lblSelectedTitle = null!;
    private Label lblSelectedCwd = null!;
    private Label lblSelectedPath = null!;
    private TextBox txtSelectedId = null!;
    private TextBox txtSelectedTitle = null!;
    private TextBox txtSelectedCwd = null!;
    private TextBox txtSelectedPath = null!;
    private GroupBox grpLog = null!;
    private TextBox txtLog = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        rootLayout = new TableLayoutPanel();
        grpPaths = new GroupBox();
        pathsLayout = new TableLayoutPanel();
        lblStateHome = new Label();
        lblAuthHome = new Label();
        lblProfilesRoot = new Label();
        lblSharedStoreHome = new Label();
        lblTargetHome = new Label();
        lblAppExe = new Label();
        txtStateHome = new TextBox();
        txtAuthHome = new TextBox();
        txtProfilesRoot = new TextBox();
        txtSharedStoreHome = new TextBox();
        txtTargetHome = new TextBox();
        txtAppExe = new TextBox();
        btnBrowseState = new Button();
        btnBrowseAuth = new Button();
        btnBrowseProfilesRoot = new Button();
        btnBrowseShared = new Button();
        btnBrowseTarget = new Button();
        btnBrowseAppExe = new Button();
        grpActions = new GroupBox();
        actionLayout = new FlowLayoutPanel();
        btnUseDefaults = new Button();
        btnLoadSessions = new Button();
        btnLoadSharedSessions = new Button();
        btnPrepareHome = new Button();
        btnImportSelected = new Button();
        btnRepairTargetHome = new Button();
        lblProfileName = new Label();
        cmbProfiles = new ComboBox();
        btnRefreshProfiles = new Button();
        btnSaveProfile = new Button();
        btnCreateEmptyProfile = new Button();
        btnRenameProfile = new Button();
        btnDeleteProfile = new Button();
        btnEditProfileContents = new Button();
        btnSetDefaultLaunchProfile = new Button();
        btnApplyProfile = new Button();
        btnImportProfile = new Button();
        btnExportProfile = new Button();
        btnLaunchDefaultProfile = new Button();
        btnManageSharedStoreDefaults = new Button();
        btnSwitchProfileAndLaunch = new Button();
        btnCloseApp = new Button();
        btnLaunchApp = new Button();
        chkOverwriteTarget = new CheckBox();
        chkRefreshUpdatedAt = new CheckBox();
        chkAddWorkspaceHint = new CheckBox();
        chkAutoSyncConfigChanges = new CheckBox();
        lblStatus = new Label();
        lblAppStatus = new Label();
        lblProviderStatus = new Label();
        lblDefaultProfileStatus = new Label();
        lblWatchStatus = new Label();
        mainSplit = new SplitContainer();
        grpSessions = new GroupBox();
        sessionsLayout = new TableLayoutPanel();
        lblSessionCount = new Label();
        sessionsGrid = new DataGridView();
        grpDetails = new GroupBox();
        detailsLayout = new TableLayoutPanel();
        lblSelectedId = new Label();
        lblSelectedTitle = new Label();
        lblSelectedCwd = new Label();
        lblSelectedPath = new Label();
        txtSelectedId = new TextBox();
        txtSelectedTitle = new TextBox();
        txtSelectedCwd = new TextBox();
        txtSelectedPath = new TextBox();
        grpLog = new GroupBox();
        txtLog = new TextBox();
        rootLayout.SuspendLayout();
        grpPaths.SuspendLayout();
        pathsLayout.SuspendLayout();
        grpActions.SuspendLayout();
        actionLayout.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)mainSplit).BeginInit();
        mainSplit.Panel1.SuspendLayout();
        mainSplit.Panel2.SuspendLayout();
        mainSplit.SuspendLayout();
        grpSessions.SuspendLayout();
        sessionsLayout.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)sessionsGrid).BeginInit();
        grpDetails.SuspendLayout();
        detailsLayout.SuspendLayout();
        grpLog.SuspendLayout();
        SuspendLayout();
        rootLayout.ColumnCount = 1;
        rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        rootLayout.Controls.Add(grpPaths, 0, 0);
        rootLayout.Controls.Add(grpActions, 0, 1);
        rootLayout.Controls.Add(mainSplit, 0, 2);
        rootLayout.Dock = DockStyle.Fill;
        rootLayout.Location = new Point(0, 0);
        rootLayout.Name = "rootLayout";
        rootLayout.RowCount = 3;
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 230F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 230F));
        rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        rootLayout.Size = new Size(1500, 940);
        rootLayout.TabIndex = 0;
        grpPaths.Controls.Add(pathsLayout);
        grpPaths.Dock = DockStyle.Fill;
        grpPaths.Location = new Point(12, 8);
        grpPaths.Margin = new Padding(12, 8, 12, 8);
        grpPaths.Name = "grpPaths";
        grpPaths.Padding = new Padding(10);
        grpPaths.Size = new Size(1476, 214);
        grpPaths.TabIndex = 0;
        grpPaths.TabStop = false;
        grpPaths.Text = "\u76ee\u5f55\u4e0e\u8def\u5f84";
        pathsLayout.ColumnCount = 3;
        pathsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150F));
        pathsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        pathsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110F));
        pathsLayout.Controls.Add(lblStateHome, 0, 0);
        pathsLayout.Controls.Add(txtStateHome, 1, 0);
        pathsLayout.Controls.Add(btnBrowseState, 2, 0);
        pathsLayout.Controls.Add(lblAuthHome, 0, 1);
        pathsLayout.Controls.Add(txtAuthHome, 1, 1);
        pathsLayout.Controls.Add(btnBrowseAuth, 2, 1);
        pathsLayout.Controls.Add(lblProfilesRoot, 0, 2);
        pathsLayout.Controls.Add(txtProfilesRoot, 1, 2);
        pathsLayout.Controls.Add(btnBrowseProfilesRoot, 2, 2);
        pathsLayout.Controls.Add(lblSharedStoreHome, 0, 3);
        pathsLayout.Controls.Add(txtSharedStoreHome, 1, 3);
        pathsLayout.Controls.Add(btnBrowseShared, 2, 3);
        pathsLayout.Controls.Add(lblTargetHome, 0, 4);
        pathsLayout.Controls.Add(txtTargetHome, 1, 4);
        pathsLayout.Controls.Add(btnBrowseTarget, 2, 4);
        pathsLayout.Controls.Add(lblAppExe, 0, 5);
        pathsLayout.Controls.Add(txtAppExe, 1, 5);
        pathsLayout.Controls.Add(btnBrowseAppExe, 2, 5);
        pathsLayout.Dock = DockStyle.Fill;
        pathsLayout.Location = new Point(10, 26);
        pathsLayout.Name = "pathsLayout";
        pathsLayout.RowCount = 6;
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        pathsLayout.Size = new Size(1456, 178);
        pathsLayout.TabIndex = 0;
        lblStateHome.AutoSize = true;
        lblStateHome.Dock = DockStyle.Fill;
        lblStateHome.Text = "\u4f1a\u8bdd\u6e90\u76ee\u5f55";
        lblStateHome.TextAlign = ContentAlignment.MiddleLeft;
        lblAuthHome.AutoSize = true;
        lblAuthHome.Dock = DockStyle.Fill;
        lblAuthHome.Text = "\u8d26\u53f7\u843d\u5730\u76ee\u5f55";
        lblAuthHome.TextAlign = ContentAlignment.MiddleLeft;
        lblProfilesRoot.AutoSize = true;
        lblProfilesRoot.Dock = DockStyle.Fill;
        lblProfilesRoot.Text = "\u5916\u90e8\u914d\u7f6e\u76ee\u5f55";
        lblProfilesRoot.TextAlign = ContentAlignment.MiddleLeft;
        lblSharedStoreHome.AutoSize = true;
        lblSharedStoreHome.Dock = DockStyle.Fill;
        lblSharedStoreHome.Text = "\u5171\u4eab\u4ed3\u76ee\u5f55";
        lblSharedStoreHome.TextAlign = ContentAlignment.MiddleLeft;
        lblTargetHome.AutoSize = true;
        lblTargetHome.Dock = DockStyle.Fill;
        lblTargetHome.Text = "\u8fd0\u884c\u76ee\u5f55";
        lblTargetHome.TextAlign = ContentAlignment.MiddleLeft;
        lblAppExe.AutoSize = true;
        lblAppExe.Dock = DockStyle.Fill;
        lblAppExe.Text = "Codex \u7a0b\u5e8f";
        lblAppExe.TextAlign = ContentAlignment.MiddleLeft;
        txtStateHome.Dock = DockStyle.Fill;
        txtStateHome.Name = "txtStateHome";
        txtAuthHome.Dock = DockStyle.Fill;
        txtAuthHome.Name = "txtAuthHome";
        txtProfilesRoot.Dock = DockStyle.Fill;
        txtProfilesRoot.Name = "txtProfilesRoot";
        txtSharedStoreHome.Dock = DockStyle.Fill;
        txtSharedStoreHome.Name = "txtSharedStoreHome";
        txtTargetHome.Dock = DockStyle.Fill;
        txtTargetHome.Name = "txtTargetHome";
        txtAppExe.Dock = DockStyle.Fill;
        txtAppExe.Name = "txtAppExe";
        btnBrowseState.Text = "\u6d4f\u89c8";
        btnBrowseState.Click += btnBrowseState_Click;
        btnBrowseAuth.Text = "\u6d4f\u89c8";
        btnBrowseAuth.Click += btnBrowseAuth_Click;
        btnBrowseProfilesRoot.Text = "\u6d4f\u89c8";
        btnBrowseProfilesRoot.Click += btnBrowseProfilesRoot_Click;
        btnBrowseShared.Text = "\u6d4f\u89c8";
        btnBrowseShared.Click += btnBrowseShared_Click;
        btnBrowseTarget.Text = "\u6d4f\u89c8";
        btnBrowseTarget.Click += btnBrowseTarget_Click;
        btnBrowseAppExe.Text = "\u6d4f\u89c8";
        btnBrowseAppExe.Click += btnBrowseAppExe_Click;
        grpActions.Controls.Add(actionLayout);
        grpActions.Dock = DockStyle.Fill;
        grpActions.Location = new Point(12, 238);
        grpActions.Margin = new Padding(12, 8, 12, 8);
        grpActions.Name = "grpActions";
        grpActions.Padding = new Padding(10);
        grpActions.Size = new Size(1476, 214);
        grpActions.TabIndex = 1;
        grpActions.TabStop = false;
        grpActions.Text = "\u64cd\u4f5c";
        actionLayout.Controls.Add(btnUseDefaults);
        actionLayout.Controls.Add(btnLoadSessions);
        actionLayout.Controls.Add(btnLoadSharedSessions);
        actionLayout.Controls.Add(btnPrepareHome);
        actionLayout.Controls.Add(btnImportSelected);
        actionLayout.Controls.Add(btnRepairTargetHome);
        actionLayout.Controls.Add(lblProfileName);
        actionLayout.Controls.Add(cmbProfiles);
        actionLayout.Controls.Add(btnRefreshProfiles);
        actionLayout.Controls.Add(btnSaveProfile);
        actionLayout.Controls.Add(btnCreateEmptyProfile);
        actionLayout.Controls.Add(btnRenameProfile);
        actionLayout.Controls.Add(btnDeleteProfile);
        actionLayout.Controls.Add(btnEditProfileContents);
        actionLayout.Controls.Add(btnSetDefaultLaunchProfile);
        actionLayout.Controls.Add(btnApplyProfile);
        actionLayout.Controls.Add(btnImportProfile);
        actionLayout.Controls.Add(btnExportProfile);
        actionLayout.Controls.Add(btnLaunchDefaultProfile);
        actionLayout.Controls.Add(btnManageSharedStoreDefaults);
        actionLayout.Controls.Add(btnSwitchProfileAndLaunch);
        actionLayout.Controls.Add(btnCloseApp);
        actionLayout.Controls.Add(btnLaunchApp);
        actionLayout.Controls.Add(chkOverwriteTarget);
        actionLayout.Controls.Add(chkRefreshUpdatedAt);
        actionLayout.Controls.Add(chkAddWorkspaceHint);
        actionLayout.Controls.Add(chkAutoSyncConfigChanges);
        actionLayout.Controls.Add(lblStatus);
        actionLayout.Controls.Add(lblAppStatus);
        actionLayout.Controls.Add(lblProviderStatus);
        actionLayout.Controls.Add(lblDefaultProfileStatus);
        actionLayout.Controls.Add(lblWatchStatus);
        actionLayout.Dock = DockStyle.Fill;
        actionLayout.FlowDirection = FlowDirection.LeftToRight;
        actionLayout.Location = new Point(10, 26);
        actionLayout.Name = "actionLayout";
        actionLayout.Padding = new Padding(0, 4, 0, 0);
        actionLayout.Size = new Size(1456, 178);
        actionLayout.TabIndex = 0;
        actionLayout.WrapContents = true;
        btnUseDefaults.AutoSize = true;
        btnUseDefaults.Text = "\u586b\u5165\u9ed8\u8ba4\u503c";
        btnUseDefaults.Click += btnUseDefaults_Click;
        btnLoadSessions.AutoSize = true;
        btnLoadSessions.Text = "\u52a0\u8f7d\u6e90\u4f1a\u8bdd";
        btnLoadSessions.Click += btnLoadSessions_Click;
        btnLoadSharedSessions.AutoSize = true;
        btnLoadSharedSessions.Text = "\u52a0\u8f7d\u5171\u4eab\u4f1a\u8bdd";
        btnLoadSharedSessions.Click += btnLoadSharedSessions_Click;
        btnPrepareHome.AutoSize = true;
        btnPrepareHome.Text = "\u51c6\u5907\u5171\u4eab\u5e03\u5c40";
        btnPrepareHome.Click += btnPrepareHome_Click;
        btnImportSelected.AutoSize = true;
        btnImportSelected.Text = "\u5bfc\u5165\u5230\u5171\u4eab\u4ed3";
        btnImportSelected.Click += btnImportSelected_Click;
        btnRepairTargetHome.AutoSize = true;
        btnRepairTargetHome.Text = "\u540c\u6b65\u8fd0\u884c\u76ee\u5f55";
        btnRepairTargetHome.Click += btnRepairTargetHome_Click;
        lblProfileName.AutoSize = true;
        lblProfileName.Margin = new Padding(18, 10, 6, 0);
        lblProfileName.Text = "\u8d26\u53f7";
        lblProfileName.TextAlign = ContentAlignment.MiddleLeft;
        cmbProfiles.DropDownStyle = ComboBoxStyle.DropDown;
        cmbProfiles.Width = 180;
        btnRefreshProfiles.AutoSize = true;
        btnRefreshProfiles.Text = "\u5237\u65b0\u8d26\u53f7";
        btnRefreshProfiles.Click += btnRefreshProfiles_Click;
        btnSaveProfile.AutoSize = true;
        btnSaveProfile.Text = "\u4ece\u5f53\u524d\u76ee\u5f55\u5165\u5e93";
        btnSaveProfile.Click += btnSaveProfile_Click;
        btnCreateEmptyProfile.AutoSize = true;
        btnCreateEmptyProfile.Text = "新建空账号";
        btnCreateEmptyProfile.Click += btnCreateEmptyProfile_Click;
        btnRenameProfile.AutoSize = true;
        btnRenameProfile.Text = "重命名账号";
        btnRenameProfile.Click += btnRenameProfile_Click;
        btnDeleteProfile.AutoSize = true;
        btnDeleteProfile.Text = "删除账号";
        btnDeleteProfile.Click += btnDeleteProfile_Click;
        btnEditProfileContents.AutoSize = true;
        btnEditProfileContents.Text = "\u7f16\u8f91\u8d26\u53f7\u5185\u5bb9";
        btnEditProfileContents.Click += btnEditProfileContents_Click;
        btnSetDefaultLaunchProfile.AutoSize = true;
        btnSetDefaultLaunchProfile.Text = "\u8bbe\u4e3a\u9ed8\u8ba4\u542f\u52a8\u8d26\u53f7";
        btnSetDefaultLaunchProfile.Click += btnSetDefaultLaunchProfile_Click;
        btnApplyProfile.AutoSize = true;
        btnApplyProfile.Text = "\u5207\u6362\u8d26\u53f7\u5e76\u540c\u6b65";
        btnApplyProfile.Click += btnApplyProfile_Click;
        btnImportProfile.AutoSize = true;
        btnImportProfile.Text = "\u5bfc\u5165\u5916\u90e8\u914d\u7f6e";
        btnImportProfile.Click += btnImportProfile_Click;
        btnExportProfile.AutoSize = true;
        btnExportProfile.Text = "\u5bfc\u51fa\u8d26\u53f7\u6587\u4ef6";
        btnExportProfile.Click += btnExportProfile_Click;
        btnLaunchDefaultProfile.AutoSize = true;
        btnLaunchDefaultProfile.Text = "\u6309\u9ed8\u8ba4\u8d26\u53f7\u542f\u52a8";
        btnLaunchDefaultProfile.Click += btnLaunchDefaultProfile_Click;
        btnManageSharedStoreDefaults.AutoSize = true;
        btnManageSharedStoreDefaults.Text = "\u7ba1\u7406\u5171\u4eab\u4ed3\u9ed8\u8ba4\u8d26\u53f7";
        btnManageSharedStoreDefaults.Click += btnManageSharedStoreDefaults_Click;
        btnSwitchProfileAndLaunch.AutoSize = true;
        btnSwitchProfileAndLaunch.Text = "\u5207\u6362\u5e76\u542f\u52a8";
        btnSwitchProfileAndLaunch.Click += btnSwitchProfileAndLaunch_Click;
        btnCloseApp.AutoSize = true;
        btnCloseApp.Text = "\u5173\u95ed Codex";
        btnCloseApp.Click += btnCloseApp_Click;
        btnLaunchApp.AutoSize = true;
        btnLaunchApp.Text = "\u540c\u6b65\u5e76\u542f\u52a8 Codex";
        btnLaunchApp.Click += btnLaunchApp_Click;
        chkOverwriteTarget.AutoSize = true;
        chkOverwriteTarget.Text = "\u8986\u76d6\u8fd0\u884c\u76ee\u5f55\u914d\u7f6e";
        chkRefreshUpdatedAt.AutoSize = true;
        chkRefreshUpdatedAt.Checked = true;
        chkRefreshUpdatedAt.CheckState = CheckState.Checked;
        chkRefreshUpdatedAt.Text = "\u5237\u65b0 updated_at";
        chkAddWorkspaceHint.AutoSize = true;
        chkAddWorkspaceHint.Checked = true;
        chkAddWorkspaceHint.CheckState = CheckState.Checked;
        chkAddWorkspaceHint.Text = "\u5199\u5165\u5de5\u4f5c\u533a\u63d0\u793a";
        chkAutoSyncConfigChanges.AutoSize = true;
        chkAutoSyncConfigChanges.Checked = true;
        chkAutoSyncConfigChanges.CheckState = CheckState.Checked;
        chkAutoSyncConfigChanges.Text = "\u76d1\u63a7\u5e76\u81ea\u52a8\u540c\u6b65\u914d\u7f6e";
        lblStatus.AutoSize = true;
        lblStatus.Margin = new Padding(18, 10, 8, 0);
        lblStatus.Text = "\u7a7a\u95f2";
        lblAppStatus.AutoSize = true;
        lblAppStatus.Margin = new Padding(18, 10, 8, 0);
        lblAppStatus.Text = "\u7a0b\u5e8f\uff1a\u672a\u77e5";
        lblProviderStatus.AutoSize = true;
        lblProviderStatus.Margin = new Padding(18, 10, 8, 0);
        lblProviderStatus.Text = "\u63d0\u4f9b\u65b9\uff1a\u672a\u77e5";
        lblDefaultProfileStatus.AutoSize = true;
        lblDefaultProfileStatus.Margin = new Padding(18, 10, 8, 0);
        lblDefaultProfileStatus.Text = "\u9ed8\u8ba4\u542f\u52a8\u8d26\u53f7\uff1a\u672a\u8bbe\u7f6e";
        lblWatchStatus.AutoSize = true;
        lblWatchStatus.Margin = new Padding(18, 10, 8, 0);
        lblWatchStatus.Text = "\u76d1\u63a7\uff1a\u672a\u77e5";
        mainSplit.Dock = DockStyle.Fill;
        mainSplit.Location = new Point(12, 388);
        mainSplit.Margin = new Padding(12, 8, 12, 12);
        mainSplit.Name = "mainSplit";
        mainSplit.Panel1.Controls.Add(grpSessions);
        mainSplit.Panel2.Controls.Add(grpLog);
        mainSplit.Panel2.Controls.Add(grpDetails);
        mainSplit.Size = new Size(1476, 540);
        mainSplit.SplitterDistance = 870;
        mainSplit.TabIndex = 2;
        grpSessions.Controls.Add(sessionsLayout);
        grpSessions.Dock = DockStyle.Fill;
        grpSessions.Location = new Point(0, 0);
        grpSessions.Name = "grpSessions";
        grpSessions.Padding = new Padding(10);
        grpSessions.Size = new Size(870, 540);
        grpSessions.TabIndex = 0;
        grpSessions.TabStop = false;
        grpSessions.Text = "\u4f1a\u8bdd\u5217\u8868";
        sessionsLayout.ColumnCount = 1;
        sessionsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        sessionsLayout.Controls.Add(lblSessionCount, 0, 0);
        sessionsLayout.Controls.Add(sessionsGrid, 0, 1);
        sessionsLayout.Dock = DockStyle.Fill;
        sessionsLayout.Location = new Point(10, 26);
        sessionsLayout.Name = "sessionsLayout";
        sessionsLayout.RowCount = 2;
        sessionsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        sessionsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        sessionsLayout.Size = new Size(850, 504);
        sessionsLayout.TabIndex = 0;
        lblSessionCount.AutoSize = true;
        lblSessionCount.Dock = DockStyle.Fill;
        lblSessionCount.Text = "\u6e90\u4f1a\u8bdd\uff1a0";
        lblSessionCount.TextAlign = ContentAlignment.MiddleLeft;
        sessionsGrid.AllowUserToAddRows = false;
        sessionsGrid.AllowUserToDeleteRows = false;
        sessionsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        sessionsGrid.BackgroundColor = SystemColors.Window;
        sessionsGrid.Dock = DockStyle.Fill;
        sessionsGrid.MultiSelect = false;
        sessionsGrid.ReadOnly = true;
        sessionsGrid.RowHeadersVisible = false;
        sessionsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        sessionsGrid.SelectionChanged += sessionsGrid_SelectionChanged;
        grpDetails.Controls.Add(detailsLayout);
        grpDetails.Dock = DockStyle.Top;
        grpDetails.Location = new Point(0, 0);
        grpDetails.Name = "grpDetails";
        grpDetails.Padding = new Padding(10);
        grpDetails.Size = new Size(602, 190);
        grpDetails.TabIndex = 0;
        grpDetails.TabStop = false;
        grpDetails.Text = "\u9009\u4e2d\u4f1a\u8bdd";
        detailsLayout.ColumnCount = 2;
        detailsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
        detailsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        detailsLayout.Controls.Add(lblSelectedId, 0, 0);
        detailsLayout.Controls.Add(txtSelectedId, 1, 0);
        detailsLayout.Controls.Add(lblSelectedTitle, 0, 1);
        detailsLayout.Controls.Add(txtSelectedTitle, 1, 1);
        detailsLayout.Controls.Add(lblSelectedCwd, 0, 2);
        detailsLayout.Controls.Add(txtSelectedCwd, 1, 2);
        detailsLayout.Controls.Add(lblSelectedPath, 0, 3);
        detailsLayout.Controls.Add(txtSelectedPath, 1, 3);
        detailsLayout.Dock = DockStyle.Fill;
        detailsLayout.Location = new Point(10, 26);
        detailsLayout.Name = "detailsLayout";
        detailsLayout.RowCount = 4;
        detailsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        detailsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        detailsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 30F));
        detailsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        detailsLayout.Size = new Size(582, 154);
        detailsLayout.TabIndex = 0;
        lblSelectedId.AutoSize = true;
        lblSelectedId.Dock = DockStyle.Fill;
        lblSelectedId.Text = "\u4f1a\u8bdd ID";
        lblSelectedId.TextAlign = ContentAlignment.MiddleLeft;
        lblSelectedTitle.AutoSize = true;
        lblSelectedTitle.Dock = DockStyle.Fill;
        lblSelectedTitle.Text = "\u6807\u9898";
        lblSelectedTitle.TextAlign = ContentAlignment.MiddleLeft;
        lblSelectedCwd.AutoSize = true;
        lblSelectedCwd.Dock = DockStyle.Fill;
        lblSelectedCwd.Text = "\u5de5\u4f5c\u76ee\u5f55";
        lblSelectedCwd.TextAlign = ContentAlignment.MiddleLeft;
        lblSelectedPath.AutoSize = true;
        lblSelectedPath.Dock = DockStyle.Fill;
        lblSelectedPath.Text = "\u4f1a\u8bdd\u6587\u4ef6";
        lblSelectedPath.TextAlign = ContentAlignment.MiddleLeft;
        txtSelectedId.Dock = DockStyle.Fill;
        txtSelectedId.ReadOnly = true;
        txtSelectedTitle.Dock = DockStyle.Fill;
        txtSelectedTitle.ReadOnly = true;
        txtSelectedCwd.Dock = DockStyle.Fill;
        txtSelectedCwd.ReadOnly = true;
        txtSelectedPath.Dock = DockStyle.Fill;
        txtSelectedPath.Multiline = true;
        txtSelectedPath.ReadOnly = true;
        txtSelectedPath.ScrollBars = ScrollBars.Vertical;
        grpLog.Controls.Add(txtLog);
        grpLog.Dock = DockStyle.Fill;
        grpLog.Location = new Point(0, 190);
        grpLog.Name = "grpLog";
        grpLog.Padding = new Padding(10);
        grpLog.Size = new Size(602, 350);
        grpLog.TabIndex = 1;
        grpLog.TabStop = false;
        grpLog.Text = "\u65e5\u5fd7";
        txtLog.Dock = DockStyle.Fill;
        txtLog.Multiline = true;
        txtLog.ReadOnly = true;
        txtLog.ScrollBars = ScrollBars.Vertical;
        AutoScaleDimensions = new SizeF(7F, 17F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1500, 940);
        Controls.Add(rootLayout);
        MinimumSize = new Size(1360, 820);
        Name = "Form1";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Codex Home \u7ba1\u7406\u5668";
        mainSplit.Panel1.ResumeLayout(false);
        mainSplit.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)mainSplit).EndInit();
        rootLayout.ResumeLayout(false);
        grpPaths.ResumeLayout(false);
        pathsLayout.ResumeLayout(false);
        pathsLayout.PerformLayout();
        grpActions.ResumeLayout(false);
        actionLayout.ResumeLayout(false);
        actionLayout.PerformLayout();
        grpSessions.ResumeLayout(false);
        sessionsLayout.ResumeLayout(false);
        sessionsLayout.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)sessionsGrid).EndInit();
        grpDetails.ResumeLayout(false);
        detailsLayout.ResumeLayout(false);
        detailsLayout.PerformLayout();
        grpLog.ResumeLayout(false);
        grpLog.PerformLayout();
        ResumeLayout(false);
    }
}




